name: examples
description: dart.dev example code.
version: 0.0.2

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  args: ^2.0.0-nullsafety.0
  examples_util:
    path: ../util
  pedantic: ^1.10.0-nullsafety.3
  # test: ^1.16.0-nullsafety.13
